# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trying Jekyll
email: mymail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  First attempt at using Jekyll, a static blog-aware site
  generator. This description also goes to document head
  meta for Google search results.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000"
twitter_username: non_twittering_bird
github_username:  ujr
author: "me"
year: 2020

# Build settings

permalink: /:categories/:year/:month/:day/:title

collections:
  authors:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM

